#!groovy

// Generated by IBM TransformationAdvisor
// Fri Apr 26 22:52:42 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'unicomersecuritywebapplicationear'
    mvnCommands = '--version'
    test='false'
}